### ISSUE TITLE
Clear button doesn't work

### ISSUE THREAD

**Issue by getaaron** [marzapower/MPNumericTextField#2]
If I set `textField.clearButtonMode = UITextFieldViewModeWhileEditing`, pressing the clear button temporarily clears the display.

However, if I tap another number, the old value returns.

**Comment by marzapower** [comment]
Thank you for letting me know. I'll try to fix this asap.

Il sabato 28 febbraio 2015, Aaron Brager notifications@github.com ha
scritto:

> If I set textField.clearButtonMode = UITextFieldViewModeWhileEditing,
> pressing the clear button temporarily clears the display.
> 
> However, if I tap another number, the old value returns.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marzapower/MPNumericTextField/issues/2.

## 

Ing. Daniele Di Bernardo
