### ISSUE TITLE
Build issues with 1.1.0 and Storyboards

### ISSUE THREAD

**Issue by travisgriggs** [marzapower/MPNumericTextField#5]
I installed 1.1.0 via CocoaPods. I used the storyboard to add an UITextInput and then changed the class to `MPNumericTextField`. This produces 2 build errors that show up when building:

file:///Users/travisg/Projects/myValve/myValve/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)

and

file:///Users/travisg/Projects/myValve/myValve/Base.lproj/Main.storyboard: error: IB Designables: Failed to render instance of MPNumericTextField: Failed to load designables from path (null)

It seems to go ahead and actually build and run the image, even though it says there were 2 build errors.

**Comment by marzapower** [comment]
Since this is a non-blocking issue, I'd suggest to switch to CocoaPods v. `0.36.0.rc.1` and add the `use_frameworks!` call in the `Podfile` as suggested by https://github.com/CocoaPods/CocoaPods/issues/2792 and http://stackoverflow.com/a/28108248/681409
